# DataTypes Attributes

# Main DataType is ndarray - n dimensional array

In [1]:
import numpy as np

In [9]:
array_1d = np.array([1,2,3])

In [10]:
type(array_1d)

numpy.ndarray

In [11]:
array_1d

array([1, 2, 3])

In [12]:
array_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [13]:
type(array_2d)

numpy.ndarray

In [14]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
array_3d = np.array([ 
                     [[1,2,3],[4,5,6], [7,8,9]],
                     [[10,11,12], [13,14,15], [16,17,18]]
                    ])

In [18]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

# Shape of ndarray

In [19]:
array_1d.shape

(3,)

In [20]:
array_2d.shape

(3, 3)

In [22]:
array_3d.shape

(2, 3, 3)

# Dimension of ndarray

In [23]:
array_1d.ndim

1

In [24]:
array_2d.ndim

2

In [25]:
array_3d.ndim

3